### ISSUE TITLE
Getting error response

### ISSUE THREAD

**Issue by AmarnathCJD** [LyoSU/quote-api#17]
**{"ok":false,"error":{"code":500,"message":"Cannot read property 'name' of undefined"}}**
Although "name" is specified

My code:

**from requests import post
url = "https://bot.lyo.su/quote/generate.png/"
data = {"type": "quote", "messages": [{"from": {"id": event.sender_id, "first_name": event.sender.first_name, "last_name": "pro", "language_code": "en", "title": "hi"}, "text": "love", "name": "pro"}]}
r = post(url, data=data)
print(r.text)**

**Comment by LyoSU** [comment]
need to send json to body

**Comment by AmarnathCJD** [comment]
It's send as post reqest data

**Comment by AmarnathCJD** [comment]
You mean as a part of url?

**Comment by LyoSU** [comment]
https://stackoverflow.com/questions/9733638/how-to-post-json-data-with-python-requests

**Comment by AmarnathCJD** [comment]
Now getting just Bad request

**from requests import post
url = "https://bot.lyo.su/quote/generate.png/"
data = {
  "type": "quote",
  "backgroundColor": "#1b1429",
  "width": 512,
  "height": 768,
  "scale": 2,
  "messages": [
    {
      "entities": [],
      "chatId": 66478514,
      "avatar": True,
      "from": {
        "id": 66478514,
        "first_name": "Yuri 💜",
        "last_name": "Ly",
        "username": "LyoSU",
        "language_code": "ru",
        "title": "Yuri 💜 Ly",
        "photo": {
          "small_file_id": "AQADAgADCKoxG7Jh9gMACBbSEZguAAMCAAOyYfYDAATieVimvJOu7M43BQABHgQ",
          "small_file_unique_id": "AQADFtIRmC4AA843BQAB",
          "big_file_id": "AQADAgADCKoxG7Jh9gMACBbSEZguAAMDAAOyYfYDAATieVimvJOu7NA3BQABHgQ",
          "big_file_unique_id": "AQADFtIRmC4AA9A3BQAB"
        },
        "type": "private",
        "name": "Yuri 💜 Ly"
      },
      "text": "I love you 💜",
      "replyMessage": {}
    }
  ]
}
headers = {'Content-type': 'application/json'}
r = post(url, data=data, headers=headers)
print(r.text)**

**Comment by LyoSU** [comment]
I do not understand python, to addition

**Comment by AmarnathCJD** [comment]
can you send an example request in js?

**Comment by LyoSU** [comment]
https://github.com/LyoSU/quote-bot/blob/master/handlers/quote.js#L345

**Comment by AmarnathCJD** [comment]
Ok all working fine
Now can you tell the format of replyMessage = {}
it's all sub classes

**Comment by LyoSU** [comment]
replyMessage like messages

**Comment by AmarnathCJD** [comment]
Nice ok about entites how to specify

**Comment by LyoSU** [comment]
https://core.telegram.org/bots/api#messageentity

**Comment by AmarnathCJD** [comment]
So more than 3req/min is paid?

**Comment by AmarnathCJD** [comment]
???🤭
