### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by AliAryanTech** [LyoSU/quote-api#35]
You recently update your API, mostly time's this error occurred ```Request failed with status code 500``` even that request is same as usual didn't change a bit, but still sometimes that error Occurred.

I already checked both json!
```json
{"type":"quote","format":"png","backgroundColor":"#FFFFFF","width":512,"height":768,"scale":2,"messages":[{"entities":[],"avatar":true,"from":{"id":1,"name":"deey","photo":{"url":"https://upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg"}},"text":"Hmmm","replyMessage":{}}]}
```
**response:** Request failed with status code 500

```json
{"type":"quote","format":"png","backgroundColor":"#FFFFFF","width":512,"height":768,"scale":2,"messages":[{"entities":[],"avatar":true,"from":{"id":1,"name":"Alι_Aryαɴ","photo":{"url":"https://telegra.ph/file/e991bb4b535a0f1425aa0.jpg"}},"text":"Hello","replyMessage":{}}]}
```
**response:** "successful"

Pretty weird, sometimes that error Occurred. else both works

**Comment by LyoSU** [comment]
Have you found a solution to the problem? I was going to watch later

**Comment by AliAryanTech** [comment]
> Have you found a solution to the problem? I was going to watch later

Nope, that error Occurred again and again, I thought this project is longer in maintenances, that's why I closed.

**Comment by LyoSU** [comment]
> I thought this project is longer in maintenances

I am working on this project in my free time. As there is a desire, I look at the problems that have accumulated and solve them

**Comment by LyoSU** [comment]
In any case, if you have the opportunity, you can send a PR with the correction of this problem.

**Comment by AliAryanTech** [comment]
> In any case, if you have the opportunity, you can send a PR with the correction of this problem.

Ok, got it
btw, don't you think your project should have some examples code for help?? Coz, first time I was also literally getting errors, that's the reason I messaged you on telegram.

**Nevermind, you can see the request code - [Here](https://github.com/AliAryanTech/Chisato-WhatsApp/blob/master/src/Commands/Utils/Quotly.ts)**

**Comment by LyoSU** [comment]
> examples code for help

Thought about it. But then again, I have a lot of other work to do. I can't do everything. But you can see the signs in my bot which uses this api:

**Comment by AliAryanTech** [comment]
> > examples code for help
> 
> Thought about it. But then again, I have a lot of other work to do. I can't do everything. But you can use the example in my bot that uses this apii: https://github.com/LyoSU/quote-bot

In bot?? Why not API repo coz, user want to know how to make request on this API

**Comment by LyoSU** [comment]
> Why not API repo

Because I don't have time. If you have it, you can help and make documentation. And I think it is necessary for a small number of people.

**Comment by AliAryanTech** [comment]
Well, it been a while since that error Occurred has been stopped. I guess it's because of package update you made. - [Here](https://github.com/LyoSU/quote-api/commit/6e27746bb3e946205cb60607a85239747b4640ef)
